front:
  template: magic/M15/Main
  colors:
    - char: u
      name: blue
      sources:
        normal: true
    - char: g
      name: green
      sources:
        normal: true
  colorOverride: []
  name: Environmental Adaptation
  manaCost:
    __type: ManaCost
    symbols: 1GU
  artImage:
    __type: image
    imageUrl: /project/cards/Placeholder%20Simic%20Spell.jpg
    width: 1440
    height: 1799
    cropWidth: 1355
    cropHeight: 956
    xOffset: 39
    yOffset: 0
  superType: Sorcery
  subType: ""
  flagLeft: ""
  flagRight: ""
  power: ""
  toughness: ""
  showPT: ""
  rarity: common
  illustrator: dzoolivier
  autoCollectorNumber: CZ13
  collectorNumber: ""
  setCode: ""
  language: ""
  legalText: ""
  showFooterOverrides: false
  faceSymbol: null
  rulesText: "Put three different counters on target creature from among: flying,
    curious, trample, and +1/+1. (Whenever a creature with a curious deals
    damage to an opponent, you may draw a card.)"
  flavorText: "The man is menagerie: leaves, scales, and a peculiar eccentricity."
  frame: auto
  artSize: auto
  crownStyle: auto
  nyxStyle: auto
  vehicleStyle: auto
  snowStyle: auto
  scrollsStyle: auto
  draftStyle: auto
  miracleStyle: auto
  ubStyle: auto
  hybridStyle: []
  hybridBlendStyle: grey
  meldStyle: none
  otherFrameOptions:
    avoidCoveringDevoid: true
  chopTop: ""
  chopBottom: ""
  maxFontSize: ""
  centerText: never
notes: ""
tags: []
baseName: Environmental Adaptation
imageExports:
  front: Environmental Adaptation - 3e56c122.jpg
